# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b83bddbfd77b2fe568d678da66b09c1ab7d1df8311d3ae83995e35089144301d0771790616c09ea84d4663a2b4abfc83b1dab96e4c6ebc09b5643a3e4c11ffb

test:
  secret_key_base: ddac787136ffada7b3a1f11e2c568159d29fd3d0684b6d7c866e9fe6aa4c38bbfe47a2a9d6df7cbec95504336140a77e55cd55fa7bf32c989393e7905a15db36

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
